server:
  port: 9001
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  application:
    name: mqtt-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/mqtt_service?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
