spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_nurse_prod?useSSL=false
    username: root
    password: Cmile#123
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 9001
  error:
    include-message: always